baseURL = 'https://blog.algorand.observer/'
languageCode = 'en-us'
title = 'Algorand Observer'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Algorand.Observer"
description = "Real-time Algorand blockchain event streaming"
keywords = [ "Algorand", "Observer", "DEX", "NFT", "Swaps" ]
author = "D13.co//ective"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = " "
  icon = "/images/logo4-white-48.png"
  iconHeight = 48

  [params.profileMode]
  enabled = true
  title = "Algorand Observer"
  subtitle = ""
  imageUrl = "images/logo4-white-160.png"
  imageWidth = 160
  imageHeight = 160
  imageTitle = "Algorand Observer logo"

    [[params.profileMode.buttons]]
    name = "Governance Realtime Voting Analytics"
    url = "https://voting.algorand.observer/"

    [[params.profileMode.buttons]]
    name = "By D13.co"
    url = "https://twitter.com/d13_co"

  [params.homeInfoParams]
  Title = "Hi there ðŸ‘‹"
  Content = "Welcome to my blog"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/Algo_Observer/"


# [params.analytics.google]
# SiteVerificationTag = "XYZabc"
# 
# [params.analytics.bing]
# SiteVerificationTag = "XYZabc"
# 
# [params.analytics.yandex]
# SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/d13co/blog.algorand.observer/tree/main/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "d13"
name = "By D13.co"
url = "https://D13.co//ective"
weight = 30

[markup.highlight]
noClasses = false

